version: '3'

services:
  nubeAPI:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: nube-docker
    container_name: nubeapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      POSTGRES_DB: ${DB_NAME}
      PORT: ${PORT}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
   image: postgres:14.3
   restart: always
   ports:
   - "5431:5432"
   environment:
     POSTGRES_USER: nube
     POSTGRES_PASSWORD: nube
     POSTGRES_DB: nube
   container_name: nubedb
   volumes:
     - ./postgres:/var/lib/postgresql/data