version: "3.9"

services:
  nest:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: nube
    container_name: nubedb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data: /var/lib/postgresql/data
