version: '3'

services:
  db:
   image: postgres:14.3
   restart: always
   ports:
   - "5431:5432"
   environment:
     POSTGRES_USER: nube
     POSTGRES_PASSWORD: nube
     POSTGRES_DB: nube
   container_name: nubedb
   volumes:
     - ./postgres:/var/lib/postgresql/data