version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: nube
      POSTGRES_DB: nubedb
    volumes:
      - ./postgres:/var/lib/postgresql/data

  anylistapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: nube-docker
    restart: always
    ports:
      - "3000:${PORT}"
    environment:
      DB_PASS: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USERNAME: "${DB_USERNAME}"
      PORT: "${PORT}"